-- ### Schema
DROP DATABASE IF EXISTS pets_db;
CREATE DATABASE pets_db;
USE pets_db;

CREATE TABLE buyer
(
	id INTEGER AUTO_INCREMENT NOT NULL,
	buyer_name VARCHAR(255) NOT NULL,
	PRIMARY KEY (id)
);

CREATE TABLE pet
(
	id INTEGER AUTO_INCREMENT NOT NULL,
	animal_breed VARCHAR(255) NOT NULL,
	animal_name VARCHAR(255) NOT NULL,
	price INTEGER NOT NULL,
	buyer_id INTEGER NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY (buyer_id) REFERENCES buyer(id)
);
